const { createClient } = supabase; const db=createClient(SUPABASE_URL,SUPABASE_ANON_KEY); const $=id=>document.getElementById(id);
const STAFF=[{id:1,name:'한동균 팀장'},{id:2,name:'김민찬 책임'},{id:3,name:'김영찬 책임'}]; const STAFF_KEY='window_quote_staff'; const state={items:[],editingId:null,detailRecord:null,detailItems:[],prices:null,staff:null};
function staffInit(){const saved=localStorage.getItem(STAFF_KEY);state.staff=STAFF.find(x=>String(x.id)===saved)||null;renderStaff();}
function renderStaff(){const gate=$('staffGate'),choices=$('staffChoices');choices.innerHTML=STAFF.map(x=>`<button class="staffChoice" data-id="${x.id}">${x.name}</button>`).join('');choices.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.staff=STAFF.find(x=>String(x.id)===b.dataset.id);localStorage.setItem(STAFF_KEY,state.staff.id);renderStaff();show('home');load();});gate.classList.toggle('hidden',!!state.staff);$('currentStaff').textContent=state.staff?`현재 담당자: ${state.staff.name}`:'';}
$('changeStaff').onclick=()=>{localStorage.removeItem(STAFF_KEY);state.staff=null;renderStaff();};
const locations={'발코니창':['입구방 발코니','입구방(2) 발코니','거실 발코니','안방 발코니','건너방 발코니','건너방(2) 발코니','주방 발코니'],'분합창':['입구방 분합','거실 분합','안방 분합','건너방 분합','주방 분합'],'내창':['입구방 내창','안방 내창','건너방 내창'],'주방창':['주방창'],'복도창':['복도형 아파트 복도창']};
const products=['F-140','F-130I','F-230W','F-230WF','F-250','F-250I']; const priceProduct={'F-130I':'F-140','F-250I':'F-250'};
async function getPrices(){if(state.prices)return state.prices;const{data,error}=await db.from('price_tables').select('*');if(error){console.error(error);throw new Error('가격표를 불러오지 못했습니다: '+error.message);}state.prices=data||[];return state.prices;}
function field(o,names){for(const n of names)if(o&&o[n]!==undefined)return o[n];return null;}
async function insertItemCompatible(payload){let p={...payload};for(let attempt=0;attempt<12;attempt++){const result=await db.from('estimate_items').insert(p);if(!result.error)return result;const msg=result.error.message||'';const m=msg.match(/Could not find the '([^']+)' column of 'estimate_items'/i);if(!m)return result;const missing=m[1];if(missing==='window_name'){delete p.window_name;p.item_name=payload.window_name;}else if(missing==='item_name'){delete p.item_name;p.name=payload.window_name;}else if(missing==='name'){delete p.name;p.location=payload.window_name;}else{delete p[missing];}}return{error:{message:'estimate_items 컬럼 호환 처리에 실패했습니다.'}};}
function show(id){['home','form','detail'].forEach(x=>$(x).classList.toggle('hidden',x!==id));}
function resetForm(){$('estimateForm').reset();$('items').innerHTML='';state.items=[];state.editingId=null;$('formTitle').textContent='새 견적 작성';$('formEyebrow').textContent='NEW ESTIMATE';$('saveBtn').textContent='견적 저장';$('message').textContent='';}
function itemName(item){return item?.window_name||item?.item_name||item?.name||item?.location||'';}
function inferKind(name){for(const[k,names]of Object.entries(locations))if(names.includes(name))return k;return '직접입력';}
function fillLocations(el,kind,selected=''){const loc=el.querySelector('.location');const list=locations[kind]||[];loc.innerHTML=list.length?list.map(x=>`<option value="${x}" ${x===selected?'selected':''}>${x}</option>`).join(''):'<option value="">직접 입력</option>';}
function addItem(d={}){const n=state.items.length+1,el=document.createElement('div');el.className='item card';el.innerHTML=`<div class="itemhead"><b class="itemNo">창 ${n}</b><button type="button" class="remove">삭제</button></div><label>창 종류<select class="kind"><option value="">선택하세요</option>${Object.keys(locations).map(k=>`<option>${k}</option>`).join('')}<option>직접입력</option></select></label><label>위치<select class="location"><option>창 종류를 먼저 선택</option></select></label><label class="custom hidden">직접 입력<input class="customName"></label><label>창 형태<select class="windowType"><option value="일반창">일반창</option><option value="고정창">고정창</option></select></label><label>적용 제품<select class="product">${products.map(p=>`<option>${p}</option>`).join('')}</select></label><button type="button" class="secondary change">제품 변경</button><div class="dims"><label>실측 가로(mm)<input type="number" class="w" inputmode="numeric" min="1" required></label><label>실측 세로(mm)<input type="number" class="h" inputmode="numeric" min="1" required></label></div><div class="result">가격은 저장 후 견적서에서 계산됩니다.</div>`;$('items').append(el);bindItem(el);state.items.push(el);if(d.kind){el.querySelector('.kind').value=d.kind;fillLocations(el,d.kind,itemName(d));el.querySelector('.custom').classList.toggle('hidden',d.kind!=='직접입력');}if(d.kind==='직접입력')el.querySelector('.customName').value=itemName(d);el.querySelector('.product').value=d.product_code||'F-140';el.querySelector('.windowType').value=(d.window_type==='fixed'||d.window_type==='고정창')?'고정창':'일반창';el.querySelector('.w').value=d.actual_width||'';el.querySelector('.h').value=d.actual_height||'';el.dataset.itemId=d.id||'';}
function renumber(){state.items.forEach((e,i)=>e.querySelector('.itemNo').textContent=`창 ${i+1}`);}
function bindItem(el){const kind=el.querySelector('.kind'),prod=el.querySelector('.product');kind.onchange=()=>{fillLocations(el,kind.value);el.querySelector('.custom').classList.toggle('hidden',kind.value!=='직접입력');if(kind.value==='분합창')prod.value='F-230WF';if(kind.value==='내창')prod.value='F-230W';if(kind.value==='주방창')prod.value='F-130I';if(kind.value==='복도창')prod.value='F-250I';renderExtraSummary();};el.querySelector('.remove').onclick=()=>{el.remove();state.items=state.items.filter(x=>x!==el);renumber();renderExtraSummary();};el.querySelector('.change').onclick=()=>prod.focus();}
function getExtras(){const size=$('sizeBand').value,old=$('oldFrame').value,equip=$('equipment').value,protection=$('protection').value;const equipment=equip==='불가'?500000:400000;const demolition=size==='20'?(old==='AL'?300000:400000):(old==='AL'?400000:500000);const map={'none':0,'1-2':140000,'3-4':170000,'5-7':200000,'8-9':230000,'10+':270000};const sash=state.items.filter(el=>el.querySelector('.kind').value==='발코니창'&&Number(el.querySelector('.h').value)>=2000).length*100000;const molding=state.items.filter(el=>['분합창','내창','주방창'].includes(el.querySelector('.kind').value)).length*55000;return {equipment,demolition,sash,molding,protection:map[protection]||0,total:equipment+demolition+sash+molding+(map[protection]||0),conditions:{size,old,equip,protection}};}function renderExtraSummary(){const e=getExtras();$('extraSummary').innerHTML='<p>장비비 <b>'+money(e.equipment)+'</b></p><p>철거비 <b>'+money(e.demolition)+'</b></p><p>사춤 / 타일 <b>'+money(e.sash)+'</b></p><p>몰딩 <b>'+money(e.molding)+'</b></p><p>보양 <b>'+money(e.protection)+'</b></p><hr><p class="grand">부가시공비 합계 <b>'+money(e.total)+'</b></p>';}function encodeExtras(memo,authorOverride=null){const author=authorOverride||state.staff||null;return (memo||'')+'\n\n[담당자 데이터]'+JSON.stringify({id:author?.id||null,name:author?.name||''})+'\n[부가시공비 데이터]'+JSON.stringify(getExtras());}function decodeStaff(memo){const m=(memo||'').match(/\[담당자 데이터\](\{.*?\})\s*\n\[부가시공비 데이터\]/s);return m?JSON.parse(m[1]):null;} function decodeExtras(memo){const m=(memo||'').match(/\[부가시공비 데이터\](\{.*\})\s*$/s);return m?JSON.parse(m[1]):null;}async function calculate(items){
 const rows=await getPrices(); let total=0;
 const out=items.map(item=>{
  const lookup=priceProduct[item.product_code]||item.product_code;
  const w=Number(item.actual_width),h=Number(item.actual_height);
  const candidates=rows.filter(p=>String(field(p,['product_code','product','model','code','product_code_name'])||'').trim()===lookup && Number(field(p,['width_mm','width','w','actual_width']))>=w && Number(field(p,['height_mm','height','h','actual_height']))>=h)
   .sort((a,b)=>Number(field(a,['width_mm','width','w','actual_width']))-Number(field(b,['width_mm','width','w','actual_width']))||Number(field(a,['height_mm','height','h','actual_height']))-Number(field(b,['height_mm','height','h','actual_height'])));
  const price=candidates[0]; if(!price)return {...item,lookup,available:false,reason:'해당 제품/치수 가격표 없음'};
  const material=Number(field(price,['material_cost','material','material_price','price_material','window_price'])||0);
  const install=Number(field(price,['installation_cost','installation','install_price','labor_cost','construction_cost'])||0);
  const direct=Number(field(price,['price','unit_price','total_price','amount'])||0);
  const amount=material+install || direct; total+=amount;
  return {...item,lookup,available:amount>0,applied_width:Number(field(price,['width_mm','width','w','actual_width'])),applied_height:Number(field(price,['height_mm','height','h','actual_height'])),material,install,amount};
 }); return{items:out,total};
}
async function load(){const{data,error}=await db.from('estimates').select('*').order('created_at',{ascending:false});if(error){$('list').innerHTML=`<div class="empty">${error.message}</div>`;return;}$('list').innerHTML='';(data||[]).forEach(r=>{const b=document.createElement('button');b.className='listrow';b.innerHTML=`<div class="listMain"><div class="listTop"><b>${r.project_name||'현장명 미입력'}</b><span> / ${r.customer_name||'고객명 미입력'}</span></div><div class="listBottom"><span>${new Date(r.created_at||Date.now()).toLocaleDateString('ko-KR')}</span><span class="statusBadge">${r.status||'작성중'}</span></div></div>`;b.onclick=()=>detail(r);$('list').append(b);});if(!data?.length)$('list').innerHTML='<div class="empty"><h3>아직 작성된 견적이 없습니다.</h3><p>첫 번째 견적을 작성해보세요.</p></div>';$('count').textContent=`${(data||[]).length}건`;}
async function detail(r){state.detailRecord=r;$('detailTitle').textContent=r.project_name||'현장명 미입력';$('dProject').textContent=r.project_name||'-';$('dCustomer').textContent=r.customer_name||'-';$('dAddress').textContent=r.address||'-';$('dDate').textContent=new Date(r.created_at||Date.now()).toLocaleDateString('ko-KR');$('dStaff').textContent=(decodeStaff(r.memo)?.name||'미지정');$('dStatus').textContent=r.status||'-';$('dMemo').textContent=(r.memo||'').replace(/\n\n\[담당자 데이터\][\s\S]*$/,'').trim()||'-';$('dTotal').textContent='계산 중...';$('dItems').innerHTML='불러오는 중...';$('dExtras').innerHTML='불러오는 중...';$('quote').classList.add('hidden');show('detail');const{data,error}=await db.from('estimate_items').select('*').eq('estimate_id',r.id).order('id');if(error){$('dTotal').textContent='항목 조회 실패';$('dItems').textContent=error.message;return;}state.detailItems=data||[];let calc={items:state.detailItems.map(x=>({...x,available:false})),total:0};let priceError='';try{calc=await calculate(state.detailItems);}catch(err){console.error(err);priceError=err?.message||'가격표 조회 실패';}const extras=decodeExtras(r.memo)||{equipment:0,demolition:0,sash:0,molding:0,protection:0,total:0};$('dItems').innerHTML=state.detailItems.length?'<table><thead><tr><th>구분</th><th>위치</th><th>제품</th><th>실측</th><th>창 형태</th><th>금액</th></tr></thead><tbody>'+calc.items.map(x=>`<tr><td>${inferKind(itemName(x))||'-'}</td><td>${itemName(x)||'-'}</td><td>${x.product_code||'-'}</td><td>${x.actual_width||'-'}×${x.actual_height||'-'}mm</td><td>${x.window_type==='fixed'?'고정창':'일반창'}</td><td>${x.available&&x.amount>0?money(x.amount):(priceError?'가격표 조회 실패':'계산 후 확인')}</td></tr>`).join('')+'</tbody></table>':'등록된 창호 항목이 없습니다.';$('dExtras').innerHTML='<table><tbody>'+[['장비비',extras.equipment],['철거비',extras.demolition],['사춤 / 타일',extras.sash],['몰딩',extras.molding],['보양',extras.protection]].map(([n,v])=>`<tr><td>${n}</td><td class="amount">${money(v||0)}</td></tr>`).join('')+`<tr class="sumRow"><th>부가시공비 합계</th><th class="amount">${money(extras.total||0)}</th></tr></tbody></table>`;calc.extras=extras;$('dTotal').textContent=priceError?'가격표 확인 필요':money(calc.total+(extras.total||0));}
function renderQuote(mode,calc){const r=state.detailRecord,customer=mode==='customer';const extras=calc.extras||decodeExtras(r.memo)||{total:0};let html=`<div class="quoteTools"><button onclick="window.print()">인쇄 / PDF 저장</button></div><div class="quoteSheet"><div class="quoteBrand">㈜ LX하우시스의 완성 창호인 LX Z:IN WINDOW 정품 창호로만 시공합니다.</div><h2>견 적 서</h2><div class="quoteHead"><p><b>견 적 일 자</b> ${new Date(r.created_at||Date.now()).toLocaleDateString('ko-KR')}</p><p><b>현 장 명</b> ${r.project_name||'-'}</p><p><b>현 장 주 소</b> ${r.address||'-'}</p><p><b>고 객 정 보</b> ${r.customer_name||'-'}</p><p><b>견 적 담 당자</b> ${decodeStaff(r.memo)?.name||'미지정'}</p></div><h3>세 부 견 적 사 항 (VAT 포함)</h3><table><thead><tr>${customer?'<th>No.</th><th>구분</th><th>위치</th><th>제품명</th><th>유리 및 두께</th><th>수량</th><th>금액</th>':'<th>No.</th><th>구분</th><th>위치</th><th>제품명</th><th>창 형태</th><th>실측</th><th>적용 치수</th><th>금액</th>'}</tr></thead><tbody>`;calc.items.forEach((x,i)=>{const name=itemName(x)||'-';const kind=inferKind(name);if(customer)html+=`<tr><td>${i+1}</td><td>${['발코니창','복도창'].includes(kind)?'외창':'내창'}</td><td>${name}</td><td>${x.product_code||'-'}</td><td>${x.window_type==='fixed'?'고정창 / 24T':'일반창 / 28T'}</td><td>1</td><td>${x.available?money(x.amount):'단가 미등록'}</td></tr>`;else html+=`<tr><td>${i+1}</td><td>${kind}</td><td>${name}</td><td>${x.product_code||'-'}</td><td>${x.window_type==='fixed'?'고정창':'일반창'}</td><td>${x.actual_width}×${x.actual_height}mm</td><td>${x.available?x.applied_width+'×'+x.applied_height+'mm':'-'}</td><td>${x.available?money(x.amount):'단가 미등록'}</td></tr>`;});html+=`</tbody></table><div class="extraBox"><h3>부가시공비</h3><p>장비비: ${money(extras.equipment)}</p><p>철거비: ${money(extras.demolition)}</p><p>사춤 / 타일: ${money(extras.sash)}</p><p>몰딩: ${money(extras.molding)}</p><p>보양: ${money(extras.protection)}</p><p><b>부가시공비 합계: ${money(extras.total)}</b></p></div><div class="total">창호 공사 금액: ${money(calc.total)}<br>부가시공비 합계: ${money(extras.total)}<br><b>총 견적 금액: ${money(calc.total+(extras.total||0))}</b></div>${customer?'<p class="muted">※ 현장 상황 및 추가 요청 사항에 따라 금액이 변경될 수 있습니다.</p>':`<p class="muted">메모: ${(r.memo||'').replace(/\n\n\[담당자 데이터\][\s\S]*$/,'')||'-'}</p>`}</div>`;$('quote').innerHTML=html;$('quote').classList.remove('hidden');}
$('newBtn').onclick=()=>{resetForm();$('sizeBand').value='20';$('oldFrame').value='AL';$('equipment').value='가능';$('protection').value='none';show('form');addItem();renderExtraSummary();};$('backBtn').onclick=$('cancelBtn').onclick=()=>show('home');$('detailBackBtn').onclick=()=>{show('home');staffInit();load();};$('editBtn').onclick=async()=>{const r=state.detailRecord;const{data,error}=await db.from('estimate_items').select('*').eq('estimate_id',r.id).order('id');if(error)return alert(error.message);$('projectName').value=r.project_name||'';$('customerName').value=r.customer_name||'';$('address').value=r.address||'';$('status').value=r.status||'작성중';$('memo').value=(r.memo||'').replace(/\n\n\[담당자 데이터\][\s\S]*$/,'');const ex=decodeExtras(r.memo);if(ex&&ex.conditions){$('sizeBand').value=ex.conditions.size;$('oldFrame').value=ex.conditions.old;$('equipment').value=ex.conditions.equip;$('protection').value=ex.conditions.protection;}$('items').innerHTML='';state.items=[];state.editingId=r.id;$('formTitle').textContent='견적 수정';$('formEyebrow').textContent='EDIT ESTIMATE';$('saveBtn').textContent='수정 저장';(data||[]).forEach(x=>addItem({...x,kind:inferKind(itemName(x))}));if(!data?.length)addItem();show('form');};$('deleteBtn').onclick=async()=>{const r=state.detailRecord;if(!confirm(`“${r.project_name}” 견적을 삭제할까요?`))return;await db.from('estimate_items').delete().eq('estimate_id',r.id);const{error}=await db.from('estimates').delete().eq('id',r.id);if(error)return alert(error.message);show('home');load();};$('internalBtn').onclick=async()=>renderQuote('internal',await calculate(state.detailItems));$('customerBtn').onclick=async()=>renderQuote('customer',await calculate(state.detailItems));$('addItem').onclick=()=>{addItem();renderExtraSummary();};['sizeBand','oldFrame','equipment','protection'].forEach(id=>$(id).onchange=renderExtraSummary);
$('estimateForm').onsubmit=async e=>{e.preventDefault();if($('saveBtn').disabled)return;$('saveBtn').disabled=true;$('message').textContent='저장 중...';try{const extras=getExtras();const rawMemo=$('memo').value;let originalAuthor=null;if(state.editingId){const existing=state.detailRecord;if(existing)originalAuthor=decodeStaff(existing.memo);}const payload={project_name:$('projectName').value,customer_name:$('customerName').value,address:$('address').value,status:$('status').value,memo:encodeExtras(rawMemo,originalAuthor||state.staff),total_amount:0};let id=state.editingId;if(id){const{error}=await db.from('estimates').update(payload).eq('id',id);if(error){$('message').textContent=error.message;return;}await db.from('estimate_items').delete().eq('estimate_id',id);}else{const{data,error}=await db.from('estimates').insert(payload).select().single();if(error){$('message').textContent=error.message;return;}id=data.id;}for(const el of state.items){const kind=el.querySelector('.kind').value,name=kind==='직접입력'?el.querySelector('.customName').value:el.querySelector('.location').value,product=el.querySelector('.product').value;const normalizedWindowType=el.querySelector('.windowType').value==='고정창'?'fixed':'normal';const itemPayload={estimate_id:id,window_name:name,product_code:product,window_type:normalizedWindowType,actual_width:Number(el.querySelector('.w').value),actual_height:Number(el.querySelector('.h').value)};const result=await insertItemCompatible(itemPayload);if(result.error){$('message').textContent=result.error.message;return;}}const{data:savedItems}=await db.from('estimate_items').select('*').eq('estimate_id',id);const calc=await calculate(savedItems||[]);await db.from('estimates').update({total_amount:calc.total+extras.total}).eq('id',id);$('message').textContent='저장되었습니다.';setTimeout(()=>{show('home');load();},500);}catch(err){console.error(err);$('message').textContent='저장 실패: '+(err?.message||err);}finally{$('saveBtn').disabled=false;}};


// 앱 초기화
staffInit();
