-- V50: 견적 변경 이력
-- 기존 estimates / estimate_items 구조는 유지하고, 견적 수정 전후 스냅샷만 별도 보관합니다.
create table if not exists public.estimate_history (
  id bigint generated by default as identity primary key,
  estimate_id uuid not null,
  action text not null default 'update',
  changed_at timestamptz not null default now(),
  staff_id bigint,
  staff_name text,
  previous_snapshot jsonb,
  next_snapshot jsonb
);
create index if not exists estimate_history_estimate_id_idx on public.estimate_history (estimate_id, changed_at desc);
